FROM oraclelinux:7.7
WORKDIR /build
RUN yum --enablerepo=ol7_optional_latest install -y gcc glibc-static
COPY src/main.c compile_and_run_tests.sh ./
RUN chmod +x compile_and_run_tests.sh
ENTRYPOINT './compile_and_run_tests.sh'
